### ISSUE TITLE
forgot a comma?

### ISSUE THREAD

**Issue by pbullion** [MusicMapIo/random-token-generator#1]
there is a missing comma after the len: 16
<img width="547" alt="screen shot 2017-01-31 at 11 15 39 am" src="https://cloud.githubusercontent.com/assets/20978249/22476066/a8c5dc52-e7a6-11e6-90b4-f6e835d81b30.png">

**Comment by wesleytodd** [comment]
Yep, that example is wrong.  Want to pr it in?
